export const demoBookings = [
  {
    id: "demo_001",
    name: "John Smith",
    email: "john@example.com",
    phone: "07123456789",
    service: "Boiler Repair",
    date: new Date().toISOString().split("T")[0],
    time: "10:00",
    notes: "Heating not working. Demo booking.",
    status: "CONFIRMED",
    paid: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo_002",
    name: "Sarah Jones",
    email: "sarah@example.com",
    phone: "07987654321",
    service: "Drain Cleaning",
    date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
    time: "11:45",
    notes: "Kitchen drain blocked. Demo booking.",
    status: "CONFIRMED",
    paid: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo_003",
    name: "Marcus Patel",
    email: "marcus@example.com",
    phone: "07555123456",
    service: "Leak Inspection",
    date: new Date(Date.now() + 172800000).toISOString().split("T")[0],
    time: "14:30",
    notes: "Water leak under bathroom sink. Demo booking.",
    status: "CONFIRMED",
    paid: true,
    createdAt: new Date().toISOString(),
  },
];

export const mockBookingResponse = (bookingId: string) => ({
  id: bookingId,
  name: "Demo User",
  email: "demo@plumbflow.com",
  phone: "07700 900000",
  service: "Boiler Repair",
  date: new Date().toISOString().split("T")[0],
  time: "10:00 AM",
  notes: "This is a demo booking to show the booking flow in action.",
  status: "CONFIRMED",
  paid: true,
  demo: true,
  createdAt: new Date().toISOString(),
});
